#!/bin/env python
# vim: ft=python

import sys, getopt, urllib, webbrowser

def usage():
  print("""
  -u  construct URL for Google's GraphViz Charts API
  -b  open that URL in the default web browser
  """)

def main():
  constructUrl = False
  showInBrowser = False

  try:
    opts, args = getopt.getopt(sys.argv[1:], "ub")
  except getopt.GetoptError, err:
    print str(err)
    usage()
    sys.exit(2)  

  for o, a in opts:
    if o == "-u":
      constructUrl = True
    elif o == "-b":
      showInBrowser = True

  graph = dict()
  graph['engine'] = 'digraph'
  graph['engine'] = 'dot'
  graph['nodes'] = []
  graph['edges'] = []

  dummy_graph = "digraph{a->b->c->a->e->b->f->g->a}"

  if constructUrl:
    query = {'cht': "gv:neato", 'chl': dummy_graph}
    url = "http://chart.googleapis.com/chart?" + urllib.urlencode(query)
    if showInBrowser:
      webbrowser.open(url)
    else:
      print(url)
  else:
    print(dummy_graph)

  
if __name__ == "__main__":
  main()
